-- ============================================================================
-- ESQUEMA SQL PARA INFORME CUATRIMESTRAL EN SUPABASE
-- ============================================================================

-- 1. Extensión de la tabla 'infoplazas' para centralizar configuración
ALTER TABLE infoplazas 
ADD COLUMN IF NOT EXISTS cant_computadoras INTEGER DEFAULT 6,
ADD COLUMN IF NOT EXISTS asociado_nombre TEXT,
ADD COLUMN IF NOT EXISTS asociado_cedula TEXT,
ADD COLUMN IF NOT EXISTS dinamizador_nombre TEXT,
ADD COLUMN IF NOT EXISTS dinamizador_cedula TEXT;

-- 2. Tabla de cabecera por Infoplaza, Año y Cuatrimestre
CREATE TABLE IF NOT EXISTS informe_cuatrimestral_header (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    infoplaza_numero INTEGER NOT NULL REFERENCES infoplazas(numero) ON DELETE CASCADE,
    anio INTEGER NOT NULL,
    cuatrimestre INTEGER NOT NULL CHECK (cuatrimestre IN (1, 2, 3)),
    cant_computadoras INTEGER DEFAULT 6,
    asociado_nombre TEXT,
    asociado_cedula TEXT,
    dinamizador_nombre TEXT,
    dinamizador_cedula TEXT,
    observaciones_generales TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_infoplaza_anio_cuatrimestre UNIQUE(infoplaza_numero, anio, cuatrimestre)
);

-- 3. Tabla de Capacitaciones, Talleres o Cursos (Punto II)
CREATE TABLE IF NOT EXISTS informe_capacitaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    informe_id BIGINT REFERENCES informe_cuatrimestral_header(id) ON DELETE CASCADE,
    infoplaza_numero INTEGER NOT NULL,
    anio INTEGER NOT NULL,
    cuatrimestre INTEGER NOT NULL,
    mes TEXT NOT NULL,
    categoria TEXT,
    tema TEXT NOT NULL,
    participantes INTEGER DEFAULT 0,
    horas NUMERIC DEFAULT 0,
    observaciones TEXT,
    orden INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asegurar columna categoria si la tabla ya existía
ALTER TABLE informe_capacitaciones ADD COLUMN IF NOT EXISTS categoria TEXT;

-- 4. Tabla de Servicios Brindados (Punto III)
CREATE TABLE IF NOT EXISTS informe_servicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    informe_id BIGINT REFERENCES informe_cuatrimestral_header(id) ON DELETE CASCADE,
    infoplaza_numero INTEGER NOT NULL,
    anio INTEGER NOT NULL,
    cuatrimestre INTEGER NOT NULL,
    servicio_nombre TEXT NOT NULL,
    ofrecido BOOLEAN DEFAULT TRUE,
    es_personalizado BOOLEAN DEFAULT FALSE,
    observaciones TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabla de Otras Actividades (Punto IV)
CREATE TABLE IF NOT EXISTS informe_otras_actividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    informe_id BIGINT REFERENCES informe_cuatrimestral_header(id) ON DELETE CASCADE,
    infoplaza_numero INTEGER NOT NULL,
    anio INTEGER NOT NULL,
    cuatrimestre INTEGER NOT NULL,
    categoria TEXT,
    actividad TEXT NOT NULL,
    participantes INTEGER DEFAULT 0,
    observaciones TEXT,
    orden INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asegurar columnas categoria y participantes si la tabla ya existía
ALTER TABLE informe_otras_actividades ADD COLUMN IF NOT EXISTS categoria TEXT;
ALTER TABLE informe_otras_actividades ADD COLUMN IF NOT EXISTS participantes INTEGER DEFAULT 0;

-- 6. Catálogo de Categorías de Capacitaciones y Otras Actividades
CREATE TABLE IF NOT EXISTS catalogo_categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL CHECK (tipo IN ('CAPACITACION', 'ACTIVIDAD')),
    nombre TEXT NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    orden INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_tipo_nombre UNIQUE(tipo, nombre)
);

-- Habilitar lectura/escritura pública con Service Role
ALTER TABLE informe_cuatrimestral_header ENABLE ROW LEVEL SECURITY;
ALTER TABLE informe_capacitaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE informe_servicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE informe_otras_actividades ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalogo_categorias ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service Role Full Access Header" ON informe_cuatrimestral_header;
DROP POLICY IF EXISTS "Service Role Full Access Capacitaciones" ON informe_capacitaciones;
DROP POLICY IF EXISTS "Service Role Full Access Servicios" ON informe_servicios;
DROP POLICY IF EXISTS "Service Role Full Access Otras Actividades" ON informe_otras_actividades;
DROP POLICY IF EXISTS "Service Role Full Access Catalogo" ON catalogo_categorias;

CREATE POLICY "Service Role Full Access Header" ON informe_cuatrimestral_header FOR ALL USING (true);
CREATE POLICY "Service Role Full Access Capacitaciones" ON informe_capacitaciones FOR ALL USING (true);
CREATE POLICY "Service Role Full Access Servicios" ON informe_servicios FOR ALL USING (true);
CREATE POLICY "Service Role Full Access Otras Actividades" ON informe_otras_actividades FOR ALL USING (true);
CREATE POLICY "Service Role Full Access Catalogo" ON catalogo_categorias FOR ALL USING (true);

-- Sembrado Inicial de Categorías de Capacitaciones y Actividades
INSERT INTO catalogo_categorias (tipo, nombre, descripcion, orden) VALUES
('CAPACITACION', 'Computación Básica', 'Aprender a usar la PC, correo e internet', 1),
('CAPACITACION', 'Ofimática', 'Manejo de Word, Excel y presentaciones', 2),
('CAPACITACION', 'Tecnología e IA', 'Programación, robótica, redes e inteligencia artificial', 3),
('CAPACITACION', 'Diseño y Multimedia', 'Edición de fotos, video y redes sociales', 4),
('CAPACITACION', 'Emprendimiento', 'Ventas, finanzas y administración de negocios', 5),
('CAPACITACION', 'Refuerzo Escolar', 'Tutorías, tareas e investigación estudiantil', 6),
('CAPACITACION', 'Oficios Prácticos', 'Reparación de PCs, electricidad o artesanías', 7),
('ACTIVIDAD', 'Ferias y Exposiciones', 'Muestras tecnológicas, comunitarias o de empleo', 1),
('ACTIVIDAD', 'Reuniones y Asambleas', 'Encuentros de vecinos, directivas o instituciones', 2),
('ACTIVIDAD', 'Cine y Recreación', 'Proyección de películas, torneos o lectura', 3),
('ACTIVIDAD', 'Trámites Ciudadanos', 'Ayuda a la gente con impresiones y trámites web', 4),
('ACTIVIDAD', 'Charlas de Salud y Ambiente', 'Prevención médica, reciclaje y seguridad', 5),
('ACTIVIDAD', 'Soporte y Mantenimiento', 'Jornadas de revisión de equipos e inventario', 6)
ON CONFLICT (tipo, nombre) DO NOTHING;

